// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoluntaryDisclosure.Persistance;

#nullable disable

namespace VoluntaryDisclosure.Persistance.Migrations
{
    [DbContext(typeof(VoluntaryDisclosureDataContext))]
    [Migration("20230528153521_Disclosures")]
    partial class Disclosures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VoluntaryDisclosure.Domain.Disclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CriminalRecord")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EthicalIndustringRestriction")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NegativeCreditListing")
                        .HasColumnType("bit");

                    b.Property<bool>("PerformanceManagementPlaced")
                        .HasColumnType("bit");

                    b.Property<bool>("RedsBankingDbListed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Disclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
